version: "3.7"
services:
  minecraft:
    image: itzg/minecraft-server
    ports:
      - "25565:25565"
    environment:
      - EULA=true
      - TYPE=PAPER
    volumes:
      - /home/worker/clocker-data/minecraft:/data
    restart: "always"
